    - name: Run tracker
      working-directory: ./  # garante que roda na raiz do repositório
      run: |
        python -m scraper.main
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
